[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# Solc settings
solc_version = "0.8.29"
optimizer = true
optimizer_runs = 200
via_ir = false

# Gas settings
gas_limit = 9223372036854775807
gas_price = 3000000000

# RPC URLs
[rpc_endpoints]
lisk_sepolia = "${LISK_SEPOLIA_RPC_URL}"


# Test settings
[profile.test]
verbosity = 2
gas_reports = ["*"]
